[package]
name = "brightflow-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "brightflow"
path = "src/main.rs"

[dependencies]
brightflow-core = { path = "../brightflow-core" }
brightflow-connect = { path = "../brightflow-connect" }
brightflow-store = { path = "../brightflow-store" }
brightflow-engine = { path = "../brightflow-engine" }
brightflow-api = { path = "../brightflow-api" }
brightflow-scheduler = { path = "../brightflow-scheduler" }

# CLI
clap = { version = "4.5", features = ["derive"] }
rpassword = "5"
anyhow = "1.0"

# Async runtime
tokio = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

# Environment
dotenvy = { workspace = true }

# Data
polars = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }

[lints]
workspace = true
