// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered website/domain that sends analytics events.
 */
export type Source = { id: string, domain: string, name: string, timezone: string, createdAt: string, updatedAt: string, };
