// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time series data point for the visitors chart.
 */
export type TimeseriesPoint = { date: string, visitors: bigint, pageviews: bigint, };
