// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a source.
 */
export type UpdateSourceRequest = { name: string | null, timezone: string | null, };
