#!/usr/bin/env bash
# Regenerate brightflow-app/src/types/generated/index.ts from the directory
# listing. Every ts-rs output file exports exactly one type named after the
# file, so the barrel is pure derived output — regenerated here (and from the
# pre-commit hook after type regen), never edited by hand.
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)/brightflow-app/src/types/generated"

{
    echo "// Auto-generated barrel over the ts-rs output — regenerated by"
    echo "// scripts/generate-ts-barrel.sh (runs from the pre-commit hook)."
    echo "// Do not edit this file manually."
    echo ""
    for f in "$DIR"/*.ts; do
        name="$(basename "$f" .ts)"
        if [ "$name" != "index" ]; then
            echo "export type { $name } from './$name';"
        fi
    done
} > "$DIR/index.ts"
