/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BigNumber: typeof import('./src/components/charts/BigNumber.vue')['default']
    BucketDropzone: typeof import('./src/components/pivot/BucketDropzone.vue')['default']
    ChartView: typeof import('./src/components/charts/ChartView.vue')['default']
    ColumnSidebar: typeof import('./src/components/layout/ColumnSidebar.vue')['default']
    DashboardLayout: typeof import('./src/components/layout/DashboardLayout.vue')['default']
    DataTable: typeof import('./src/components/results/DataTable.vue')['default']
    FilterBar: typeof import('./src/components/query/FilterBar.vue')['default']
    FilterPanel: typeof import('./src/components/pivot/FilterPanel.vue')['default']
    FilterRow: typeof import('./src/components/query-builder/FilterRow.vue')['default']
    FilterSection: typeof import('./src/components/query-builder/FilterSection.vue')['default']
    GroupBySection: typeof import('./src/components/query-builder/GroupBySection.vue')['default']
    LimitSection: typeof import('./src/components/query-builder/LimitSection.vue')['default']
    NotebookEditor: typeof import('./src/components/notebook/NotebookEditor.vue')['default']
    PivotConfig: typeof import('./src/components/pivot/PivotConfig.vue')['default']
    PivotTable: typeof import('./src/components/pivot/PivotTable.vue')['default']
    QueryBuilder: typeof import('./src/components/query/QueryBuilder.vue')['default']
    QuerySection: typeof import('./src/components/query-builder/QuerySection.vue')['default']
    ResultsPanel: typeof import('./src/components/results/ResultsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortPanel: typeof import('./src/components/pivot/SortPanel.vue')['default']
    SortSection: typeof import('./src/components/query-builder/SortSection.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardPanel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  }
}
