/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsView: typeof import('./src/components/analytics/AnalyticsView.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BigNumber: typeof import('./src/components/charts/BigNumber.vue')['default']
    BucketDropzone: typeof import('./src/components/pivot/BucketDropzone.vue')['default']
    ChartView: typeof import('./src/components/charts/ChartView.vue')['default']
    ConnectorCard: typeof import('./src/components/connect/ConnectorCard.vue')['default']
    ConnectorDashboard: typeof import('./src/components/tools/ConnectorDashboard.vue')['default']
    ConnectorSourceSettings: typeof import('./src/components/settings/ConnectorSourceSettings.vue')['default']
    DatasetPickerModal: typeof import('./src/components/layout/DatasetPickerModal.vue')['default']
    DataTable: typeof import('./src/components/results/DataTable.vue')['default']
    EventListPanel: typeof import('./src/components/analytics/EventListPanel.vue')['default']
    ExploreTablePicker: typeof import('./src/components/explore/ExploreTablePicker.vue')['default']
    ExploreTool: typeof import('./src/components/explore/ExploreTool.vue')['default']
    FilterBar: typeof import('./src/components/query/FilterBar.vue')['default']
    FunnelPanel: typeof import('./src/components/analytics/FunnelPanel.vue')['default']
    InsightCard: typeof import('./src/components/insights/InsightCard.vue')['default']
    InsightsPanel: typeof import('./src/components/insights/InsightsPanel.vue')['default']
    InsightsView: typeof import('./src/components/insights/InsightsView.vue')['default']
    LoginPage: typeof import('./src/components/auth/LoginPage.vue')['default']
    NewSourcePage: typeof import('./src/components/sources/NewSourcePage.vue')['default']
    PeriodSelector: typeof import('./src/components/layout/PeriodSelector.vue')['default']
    PivotTable: typeof import('./src/components/pivot/PivotTable.vue')['default']
    PreferencesPage: typeof import('./src/components/preferences/PreferencesPage.vue')['default']
    PresetForm: typeof import('./src/components/connect/PresetForm.vue')['default']
    ProductAnalyticsView: typeof import('./src/components/analytics/ProductAnalyticsView.vue')['default']
    QueryBuilder: typeof import('./src/components/query/QueryBuilder.vue')['default']
    ResultsPanel: typeof import('./src/components/results/ResultsPanel.vue')['default']
    RetentionPanel: typeof import('./src/components/analytics/RetentionPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunHistoryTable: typeof import('./src/components/connect/RunHistoryTable.vue')['default']
    ScheduleList: typeof import('./src/components/connect/ScheduleList.vue')['default']
    SchedulesPanel: typeof import('./src/components/connect/SchedulesPanel.vue')['default']
    SchedulesView: typeof import('./src/components/schedules/SchedulesView.vue')['default']
    SourceCard: typeof import('./src/components/layout/SourceCard.vue')['default']
    SourceLanding: typeof import('./src/components/layout/SourceLanding.vue')['default']
    SourceLayout: typeof import('./src/components/layout/SourceLayout.vue')['default']
    SyncStatusBadge: typeof import('./src/components/connect/SyncStatusBadge.vue')['default']
    SystemView: typeof import('./src/components/system/SystemView.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardToolbar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UserExplorerPanel: typeof import('./src/components/analytics/UserExplorerPanel.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    WebDashboard: typeof import('./src/components/tools/WebDashboard.vue')['default']
    WebSourceSettings: typeof import('./src/components/settings/WebSourceSettings.vue')['default']
    WelcomePage: typeof import('./src/components/layout/WelcomePage.vue')['default']
  }
}
